# Generated by Django 4.2.5 on 2025-07-27 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookname', models.CharField(max_length=100)),
                ('bookid', models.CharField(max_length=100, unique=True)),
                ('bookauthor', models.CharField(max_length=100)),
                ('publishyear', models.CharField(max_length=100)),
                ('price', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=1000)),
                ('stock', models.CharField(max_length=100)),
                ('cover_image', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'Book',
            },
        ),
        migrations.CreateModel(
            name='FattigueInfoModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=100)),
                ('login_user', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('vehiclenumber', models.CharField(max_length=100)),
                ('lattitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('fatigue', models.CharField(max_length=100)),
                ('c_date', models.DateField()),
            ],
            options={
                'db_table': 'FatigueInfo',
            },
        ),
        migrations.CreateModel(
            name='HelmetInfoModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=100)),
                ('login_user', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('vehiclenumber', models.CharField(max_length=100)),
                ('lattitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('Helmet', models.CharField(max_length=100)),
                ('c_date', models.DateField()),
            ],
            options={
                'db_table': 'HelmetInfo',
            },
        ),
        migrations.CreateModel(
            name='userRegisterModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.CharField(max_length=25, unique=True)),
                ('name', models.CharField(max_length=25)),
                ('email', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=25)),
                ('mobile', models.CharField(max_length=12)),
                ('address', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'userRegister',
            },
        ),
        migrations.CreateModel(
            name='UserRegistrationModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('loginid', models.CharField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('mobile', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('locality', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=1000)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'UserRegistration',
            },
        ),
    ]
