# Generated by Django 4.2.5 on 2025-07-27 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('bookid', models.CharField(max_length=100)),
                ('bookname', models.CharField(max_length=100)),
                ('price', models.CharField(max_length=100)),
                ('quantity', models.IntegerField(default=1)),
            ],
            options={
                'db_table': 'Cart',
            },
        ),
        migrations.DeleteModel(
            name='FattigueInfoModel',
        ),
    ]
