# Generated by Django 4.2.5 on 2025-07-28 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_cartmodel_delete_fattigueinfomodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('booknames', models.CharField(max_length=255)),
                ('bookids', models.CharField(max_length=255)),
                ('total_price', models.CharField(max_length=100)),
                ('quantities', models.CharField(max_length=100)),
                ('delivery_address', models.TextField()),
                ('payment_mode', models.CharField(max_length=100)),
                ('card_details', models.CharField(blank=True, max_length=100, null=True)),
                ('payment_status', models.CharField(max_length=100)),
                ('delivery_status', models.CharField(default='Pending', max_length=100)),
                ('order_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'Orders',
            },
        ),
        migrations.DeleteModel(
            name='HelmetInfoModel',
        ),
        migrations.DeleteModel(
            name='userRegisterModel',
        ),
    ]
